language: python
python:
  - 3.6
dist: xenial

branches:
  only:
    - staging
    - trying

sudo: false

addons:
  apt:
    packages:
      - ninja-build
      - libsdl2-dev

before_script:
  pip install meson

script:
  - mkdir _build
  - cd _build
  - meson ..
  - ninja test
